# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('perma', models.CharField(max_length=50, unique=True, verbose_name='Perma')),
                ('size', models.IntegerField(verbose_name='Size')),
                ('logo', models.ImageField(null=True, upload_to='logos/')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_valid', models.BooleanField(default=False)),
                ('barcode_active', models.BooleanField(default=False)),
                ('table_valid', models.BooleanField(default=False)),
                ('table_active', models.BooleanField(default=False)),
                ('scanned', models.DateTimeField(editable=False)),
                ('barcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barcode.Barcode')),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Enterprise')),
            ],
            options={
                'ordering': ['barcode', '-scanned'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('barcode', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barcode.Barcode')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Table'),
        ),
    ]
