# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['name']},
        ),
    ]
