# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='perma',
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size'),
        ),
    ]
