# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_auto_20180603_0552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log2',
            new_name='Log',
        ),
    ]
