# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_auto_20180603_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='log',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='log',
            name='table',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
