# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-06 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20181001_0003'),
        ('enterprise', '0003_biotlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotlog',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Line'),
        ),
    ]
