# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_auto_20180728_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Enterprise'),
        ),
        migrations.AlterField(
            model_name='log',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Table'),
        ),
    ]
