# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
        ('enterprise', '0004_auto_20180603_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_valid', models.BooleanField(default=False)),
                ('barcode_active', models.BooleanField(default=False)),
                ('table_valid', models.BooleanField(default=False)),
                ('table_active', models.BooleanField(default=False)),
                ('scanned', models.DateTimeField(editable=False)),
                ('barcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barcode.Barcode')),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Enterprise')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Table')),
            ],
            options={
                'ordering': ['barcode', '-scanned'],
            },
        ),
    ]
