# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_biotlog_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency'),
        ),
    ]
