# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_auto_20180821_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
    ]
