# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barcode.Barcode'),
        ),
    ]
