# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 23:26
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_enterprise_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='logo_cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x430', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='logo cropping'),
        ),
    ]
