# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_enterprise_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size'),
        ),
    ]
