# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_auto_20180824_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='logo_cropping',
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size'),
        ),
    ]
