# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-scanned']},
        ),
    ]
