# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_auto_20181016_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='client_address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Client Address'),
        ),
        migrations.AddField(
            model_name='table',
            name='client_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='table',
            name='client_phone',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Client Phone'),
        ),
    ]
