# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0009_auto_20180824_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='logo',
        ),
        migrations.AddField(
            model_name='logo',
            name='enterprise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise'),
        ),
    ]
