# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0010_auto_20180824_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
