# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='enterprise',
        ),
    ]
