# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_auto_20180824_1758'),
        ('account', '0004_remove_profile_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Enterprise'),
        ),
    ]
