#!/bin/sh

DATE=`date +%Y-%m-%d`
pg_dump -U postgres -h localhost exammodule > backups/exammodule/$DATE.bak
pg_dump -U postgres -h localhost classnfc > backups/classnfc/$DATE.bak

for file in `find /root/backups/ -mtime +30 -type f`
do
  rm $file
done

exit 0
