# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(editable=False)),
                ('complatedDate', models.DateTimeField(null=True)),
                ('paidDate', models.DateTimeField(null=True)),
                ('isComplated', models.BooleanField(default=False)),
                ('isPaid', models.BooleanField(default=False)),
                ('totalPrice', models.FloatField(null=True)),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Enterprise')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Table')),
            ],
            options={
                'ordering': ['-orderDate'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('options', models.CharField(max_length=300, verbose_name='Options')),
                ('optionsReadable', models.CharField(max_length=300, null=True, verbose_name='Options Readable')),
                ('price', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Enterprise')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Line')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Menu')),
            ],
            options={
                'ordering': ['-menu'],
            },
        ),
    ]
