# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('cart', '0002_line_iscommented'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300, verbose_name='Comment')),
                ('commentDate', models.DateTimeField(null=True)),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Enterprise')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Line')),
            ],
            options={
                'ordering': ['-commentDate'],
            },
        ),
    ]
