# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise'),
        ),
        migrations.AlterField(
            model_name='order',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise'),
        ),
        migrations.AlterField(
            model_name='order',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Line'),
        ),
    ]
