# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_line_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='canceledDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='isCanceled',
            field=models.BooleanField(default=False),
        ),
    ]
