# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-03 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='isPrinted',
            field=models.BooleanField(default=False),
        ),
    ]
