# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Description'),
        ),
    ]
