# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180629_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='pictures',
            new_name='picture',
        ),
    ]
