# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180605_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraMaterialSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('price', models.FloatField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ExtraMaterial')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
