# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180828_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(null=True),
        ),
    ]
