# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_extramaterialsub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extramaterialsub',
            name='option',
        ),
        migrations.AddField(
            model_name='extramaterial',
            name='option',
            field=models.ManyToManyField(to='menu.ExtraMaterialSub'),
        ),
    ]
