# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180719_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubMenuCategory',
            new_name='MenuSubCategory',
        ),
        migrations.RenameModel(
            old_name='SubMenuCategoryOption',
            new_name='MenuSubCategoryOption',
        ),
    ]
