# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180721_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusubcategoryoption',
            name='menu',
        ),
    ]
