# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('menu', '0004_auto_20180903_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering']},
        ),
    ]
