# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_category_enterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extramaterial',
            name='option',
        ),
        migrations.AddField(
            model_name='extramaterialsub',
            name='menu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extramaterialsub',
            name='option',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='menu.ExtraMaterial'),
            preserve_default=False,
        ),
    ]
