# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20180918_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biot',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='Menü Seçimi Yapınız'),
        ),
    ]
