# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20180920_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='menus/'),
        ),
    ]
