# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20180605_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='SubMenuCategoryOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('price', models.FloatField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('subMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.SubMenuCategory')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.RemoveField(
            model_name='extramaterial',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='extramaterialsub',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='extramaterialsub',
            name='option',
        ),
        migrations.DeleteModel(
            name='ExtraMaterial',
        ),
        migrations.DeleteModel(
            name='ExtraMaterialSub',
        ),
    ]
