# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20180605_0224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubMenuCategoryOptions',
            new_name='SubMenuCategoryOption',
        ),
    ]
