# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_submenucategory_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenucategoryoption',
            name='type',
            field=models.CharField(choices=[('Option', 'option'), ('Drop-Add', 'dropadd')], default='option', max_length=100, verbose_name='Type'),
        ),
    ]
