# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_submenucategoryoption_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenucategoryoption',
            name='type',
        ),
        migrations.AddField(
            model_name='submenucategory',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenucategory',
            name='type',
            field=models.CharField(choices=[('Option', 'option'), ('Drop-Add', 'dropadd')], default='option', max_length=100, verbose_name='Type'),
        ),
    ]
