# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20180615_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenucategoryoption',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='submenucategory',
            name='type',
            field=models.CharField(choices=[('option', 'Option'), ('dropadd', 'Drop-Add')], default='option', max_length=100, verbose_name='Type'),
        ),
    ]
