# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0009_auto_20180605_0151'),
        ('menu', '0012_auto_20180615_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('options', models.CharField(max_length=300, verbose_name='Options')),
                ('price', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('orderDate', models.DateTimeField(editable=False)),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Enterprise')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Menu')),
            ],
            options={
                'ordering': ['-orderDate'],
            },
        ),
    ]
