# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complatedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='isComplated',
            field=models.BooleanField(default=False),
        ),
    ]
