# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0009_auto_20180605_0151'),
        ('order', '0002_auto_20180624_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(editable=False)),
                ('complatedDate', models.DateTimeField(null=True)),
                ('isComplated', models.BooleanField(default=False)),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Enterprise')),
            ],
            options={
                'ordering': ['-orderDate'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-menu']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='complatedDate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isComplated',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderDate',
        ),
        migrations.AddField(
            model_name='line',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
    ]
