# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180624_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='optionsReadable',
            field=models.CharField(max_length=300, null=True, verbose_name='Options Readable'),
        ),
    ]
