# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_optionsreadable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Line'),
        ),
    ]
