# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180624_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
