# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_line_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='totalPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
