# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_line_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='totalPrice',
            field=models.FloatField(null=True),
        ),
    ]
